In [227]:
from bs4 import BeautifulSoup as bf
import urllib3
import numpy as np
from sklearn.metrics import r2_score
import math

In [206]:
http = urllib3.PoolManager()
r = http.request('GET', 'https://www.avito.ru/rossiya/avtomobili?s_trg=4&f=')
soup = bf(r.data, 'html.parser')
print(len([price.text for price in soup.find_all('span', {"class": "price"})]))

0


c:\users\dinmuhametov salavat\appdata\local\programs\python\python36\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)


In [76]:
param = {
    "mark":"skoda",
    "model":"octavia",
    "body":["sedan", "limusin"],
    "engine":[0.0, 6.0],
    "year":[1960, 2019],
    
}


In [77]:
def get_avito_url(prm):
    base = 'https://www.avito.ru/rossiya/avtomobili'
    try:
        base += "/"+ prm['mark']
    except (KeyError, TypeError):
        pass
    try:
        base += '/'+prm['model']
    except (KeyError, TypeError):
        pass
    base += '?s_trg=4&f='
    try:
        base += get_type_range_url('body', prm['body'])
    except (KeyError, TypeError):
        pass
    try:
        base += '.'+get_range_url('year',prm['year'])
    except (KeyError, TypeError):
        pass
    try:
        base += '.'+get_type_range_url('kpp', prm['kpp'])
    except (KeyError, TypeError):
        pass
    try:
        base += '.'+get_range_url('engine', prm['engine'])
    except (KeyError, TypeError):
        pass
    return base
print(get_avito_url(param))

https://www.avito.ru/rossiya/avtomobili/skoda/octavia?s_trg=4&f=187_869-867.188_0b405242.1374_0b15830


In [95]:
body + year + kpp + engine

NameError: name 'body' is not defined

In [13]:
def get_range_url(name, prms):
    base = multiple_params[name]['base']
    all_params = list(multiple_params[name])
    a1, a2=-1,-1
    for pr in all_params:
        if pr != 'base':
            if float(prms[0])<=float(pr):
                a1 = multiple_params[name][pr]
                break
    for pr in all_params:
        if pr != 'base':
            if float(prms[1])<=float(pr):
                a2 = multiple_params[name][pr]
                break
    return str(base)+'_'+str(a1)+'b'+str(a2)
get_range_url('year', [2012,2019])

'188_6045b405242'

In [14]:
def get_type_range_url(name, prms):
    first, second = multiple_params[name][prms[0]], multiple_params[name][prms[1]]
    base = multiple_params[name]['base']
    return str(base)+'_'+str(first)+'-'+str(second)
print(get_type_range_url('kpp', ['mechanika', 'robot']))

185_861-14754


In [75]:
multiple_params = {
   'kpp':{
       'base':185,
       'mechanika':861,
       'avtomat':860,
       'robot':14754,
       'vibator':14753,
       },
    'year':{
        'base':188,
        '1960':0,
        '1970':782,
        '2012':6045,
        '2019':405242,
    },
    'body':{
        'base':187,
        'sedan':869,
        'limusin':867,
        'chechbeck':872
    },
    'engine':{
        'base':1374,
        '0.0':0,
        '0.6':15776,
        '5.5':15825,
        '6.0':15830
    },
    'mark':{
        'skoda':['octavia', 'rapid'],
        'vaz_lada':['kalina', 'granta'],
        'kia':['rio','spectra']
    },    
}

In [70]:
list(multiple_params[list(prms)[0]])

['base', '0.0', '0.6', '5.5', '6.0']

In [72]:
multiple_params[list(prms)[0]]['base']

1374

In [26]:
y = {'gobno':10}

In [32]:
try:
    y['d']
except:
    pass

In [ ]:
my_auto()

In [70]:
np.corrcoef([[2,1, 123333],[2,1, 123333],[23,3, 2343234]], [2,1, 12])

array([[1.        , 1.        , 1.        , 0.99661647],
       [1.        , 1.        , 1.        , 0.99661647],
       [1.        , 1.        , 1.        , 0.9966165 ],
       [0.99661647, 0.99661647, 0.9966165 , 1.        ]])

In [133]:
ur = 'https://www.avito.ru/rossiya/avtomobili/skoda/octavia?s_trg=4&f=187_869-867.188_0b405242.1374_0b15830'

dt = http.request('GET', ur)
soup_in = bf(dt.data, 'html.parser')

def get_data(soup):
    return [price.text for price in soup.find_all('div', {"class": "specific-params specific-params_block"})]

def get_money(soup):
    return [price.text for price in soup.find_all('span', {"class": "price"})]

def get_year(soup):
    return [price.text for price in soup.find_all('a', {"class": "item-description-title-link"})]

# shit = get_year()[:2]

# shit = get_data('https://www.avito.ru/rossiya/avtomobili/s_probegom/skoda/octavia/bityy?s_trg=4&f=187_867-869.1374_0b15830')[:2]

c:\users\dinmuhametov salavat\appdata\local\programs\python\python36\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)


In [141]:
raw_data = [preparsing(d) for d in get_data(soup_in)]
x_money = [money_prepros(d) for d in get_money(soup_in)]
x_year = [year_prepros(d) for d in get_year(soup_in)]
print(len(raw_data), len(x_money), len(x_year))

54 54 54


In [124]:
def money_prepros(req):
    return req.replace(' ', '').replace('\n', '').replace('₽', '')
def year_prepros(req):
    return req.split(',')[1].replace(' ','')
def preparsing(shit):
    return [st.replace('\xa0', ' ').replace('\n', '').replace(' ', '') for st in shit.split(',')]

In [49]:
#dispersa_anal
#bitaya 1, 0
#priceK
#milescore
#year
#dvigatel

In [150]:
def create_train_x(money, year, request):
    train_x = []
    for rq in request:
        is_brouken = 0
        km = 0
        at,mt,amt=0,0,0
        house_power = 0
        engine_v = 0
        for i in range(len(rq)):
            if rq[i].find('Битый') != -1:
                is_brouken = 1
            if rq[i].find('км') != -1:
                km = int(rq[i].replace('км', ''))
            if rq[i].find('AT') != -1:
                at=1
            if rq[i].find('MT') != -1:
                mt=1
            if rq[i].find('AMT') != -1:
                amt=1
            if rq[i].find('л.с.') != -1:
                house_power = int(rq[i][rq[i].find('(')+1:rq[i].find('л')])
                engine_v = float(rq[i][rq[i].find('.')-1:rq[i].find('.')+2])
            if x_money[i] == 0 or x_year[i] == 0 or house_power==0 or engine_v==0 or km==0:
                continue
            train_x.append([is_brouken,x_money[i],km,x_year[i], at,mt,amt,engine_v,house_power])
    return train_x

create_train_x(x_money, x_year, raw_data)

[[0, '555000', 89000, '2013', 1, 0, 0, 1.8, 180],
 [0, '845000', 89000, '2014', 1, 0, 0, 1.8, 180],
 [0, '495000', 89000, '2012', 1, 0, 0, 1.8, 180],
 [0, '460000', 89000, '2014', 1, 0, 0, 1.8, 180],
 [0, '555000', 67600, '2013', 0, 1, 1, 1.4, 140],
 [0, '845000', 67600, '2014', 0, 1, 1, 1.4, 140],
 [0, '495000', 67600, '2012', 0, 1, 1, 1.4, 140],
 [0, '460000', 67600, '2014', 0, 1, 1, 1.4, 140],
 [0, '555000', 72000, '2013', 0, 1, 0, 1.4, 122],
 [0, '845000', 72000, '2014', 0, 1, 0, 1.4, 122],
 [0, '495000', 72000, '2012', 0, 1, 0, 1.4, 122],
 [0, '460000', 72000, '2014', 0, 1, 0, 1.4, 122],
 [0, '555000', 210000, '2013', 1, 0, 0, 1.2, 105],
 [0, '845000', 210000, '2014', 1, 0, 0, 1.2, 105],
 [0, '495000', 210000, '2012', 1, 0, 0, 1.2, 105],
 [0, '460000', 210000, '2014', 1, 0, 0, 1.2, 105],
 [0, '555000', 86000, '2013', 0, 1, 0, 1.6, 102],
 [0, '845000', 86000, '2014', 0, 1, 0, 1.6, 102],
 [0, '495000', 86000, '2012', 0, 1, 0, 1.6, 102],
 [0, '460000', 86000, '2014', 0, 1, 0, 1.6, 10

In [151]:
train_x = create_train_x(x_money, x_year, raw_data)
test_x = [0, 250000, 128500, 2001,1,0,0,1.8,150]

In [167]:
coor = np.corrcoef(np.array(train_x).astype(np.float), np.array(test_x).astype(np.float))

In [165]:
np.array(train_x).astype(np.float)

array([[0.00000e+00, 5.55000e+05, 8.90000e+04, ..., 0.00000e+00,
        1.80000e+00, 1.80000e+02],
       [0.00000e+00, 8.45000e+05, 8.90000e+04, ..., 0.00000e+00,
        1.80000e+00, 1.80000e+02],
       [0.00000e+00, 4.95000e+05, 8.90000e+04, ..., 0.00000e+00,
        1.80000e+00, 1.80000e+02],
       ...,
       [0.00000e+00, 8.45000e+05, 1.38206e+05, ..., 0.00000e+00,
        1.80000e+00, 1.52000e+02],
       [0.00000e+00, 4.95000e+05, 1.38206e+05, ..., 0.00000e+00,
        1.80000e+00, 1.52000e+02],
       [0.00000e+00, 4.60000e+05, 1.38206e+05, ..., 0.00000e+00,
        1.80000e+00, 1.52000e+02]])

In [164]:
np.array(test_x).astype(np.float)

array([0.000e+00, 2.500e+05, 1.285e+05, 2.001e+03, 1.000e+00, 0.000e+00,
       0.000e+00, 1.800e+00, 1.500e+02])

In [161]:
test_x

[0, 250000, 128500, 2001, 1, 0, 0, 1.8, 150]

In [172]:
np.array([coor[i][-1] for i in range(len(coor))]).mean()

0.9604958391382002

In [175]:
#множественный r
def get_coor_coef(train_x, train_y):
    coor = np.corrcoef(np.array(train_x).astype(np.float), np.array(test_x).astype(np.float))
    return np.array([coor[i][-1] for i in range(len(coor))]).mean()

In [219]:
def get_r_sq(train_x, train_y):
    scores = [r2_score(np.array(test_x).astype(np.float64), np.array(train_x[i]).astype(np.float64)) for i in range(len(train_x))]
    return sum(scores)/len(scores)

In [184]:
sq = np.array([[1, 3], [3,4]])-np.array([2, 4])
ss1 = sum(sum([it**2 for it in sq]))
print(ss1)

3


In [217]:
scores = [r2_score(np.array(test_x).astype(np.float64), np.array(train_x[i]).astype(np.float64)) for i in range(len(train_x))]

In [218]:
print(sum(scores)/len(scores))

-1.2564200246331763


In [221]:
np.array(test_x).astype(np.float64).var()

6990730532.008889

In [223]:
#norm r
def get_norm_r(r, n, p):
    return 1-(1-p)*(n-1)/(n-p-1)

In [230]:
get_norm_r(get_coor_coef(train_x, test_x), len(train_x), len(train_x)-len(train_x[0]))

5328.75

In [240]:
std = math.sqrt(np.array(train_x).astype(np.float64).var())

In [241]:
print(std)

192541.63182403534


In [237]:
np_money = np.array(x_money).astype(np.float64)

In [238]:
print(np_money.std(), np_money.mean())

223164.1720368267 509883.31481481483


In [239]:
np_money

array([1130000.,  555000.,  845000.,  495000.,  460000.,  570000.,
        499000.,  690000.,  344000.,  435000.,  625000.,  170000.,
        760000.,  420000.,  250000.,  245000.,  430000.,  585000.,
        629000.,  429000.,  225000.,  499000.,  120000.,  433000.,
        630000.,  450000.,  485000.,  235000.,  279000.,  320000.,
        470000.,  670000.,  420000.,  560000.,  735700.,  850000.,
        455000.,  698000.,  699999.,  470000.,  800000.,  535000.,
        679000.,  325000.,  285000.,  385000.,  419000.,  420000.,
       1350000.,  487000.,  260000.,  299000.,  540000.,  479000.])